### ISSUE TITLE
Travis-CI failures

### ISSUE THREAD

**Issue by polettix** [melezhik/web-service-fake-smoke#1]
Hi!

While updating [WebService::Fake](https://github.com/polettix/WebService-Fake) I hit this issue on Travis-CI (all perl version from 5.10 up to 5.24):

    $ sparrow plg install web-service-fake-smoke
    unknown plugin at /home/travis/perl5/perlbrew/perls/5.24.0/lib/site_perl/5.24.0/Sparrow/Commands/Plugin.pm line 275.
  	Sparrow::Commands::Plugin::install_plugin("web-service-fake-smoke") called at /home/travis/perl5/perlbrew/perls/5.24/bin/sparrow line 36
    The command "sparrow plg install web-service-fake-smoke" failed and exited with 255 during .

It seems that [the plugin is there in sparrowhub](https://sparrowhub.org/info/web-service-fake-smoke) though... ideas?

I don't know if you can access them, but [here's the link to the full build reports in Travis-CI](https://travis-ci.org/polettix/WebService-Fake/builds/432802481), where I extracted the error above.

Thanks, Flavio.

**Comment by melezhik** [comment]
Hi Flavio! I believe https://github.com/polettix/WebService-Fake/pull/4 fixes the issue. Old versions of Sparrow  runs  `sparrow index update` command by default,  while new ones do not, so before installing anything one should run `sparrow index update`.  So the issue stared with new Sparrow releases.
